accounts/urls.py
from django.urls import path
from . import views
# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.loginf, name='login'),
    # path('login/', views.LogInView.as_view(), name='login'),
]

coupleproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talk.urls')),
    path('accounts/', include('accounts.urls')), # [追加]
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

talk/urls.py
from django.urls import path, include
from .views import TalkViewBase
from django.conf import settings
from django.conf.urls.static import static

app_name = 'talk'
urlpatterns = [
    path('', TalkViewBase.as_view(), name='list'), #urlの作り込み, classはas_viewをつける
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

talk/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class TalkType(models.Model):
    name = models.CharField(verbose_name=('カテゴリー'), max_length=100)
    
    _admin_list_display = ['name']

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "カテゴリー"


class TalkModel(models.Model):
    talk        = models.TextField(verbose_name=('メッセージ'))
    read        = models.CharField(verbose_name=('既読'), max_length=100)
    created_at  = models.DateField(verbose_name=('日時'))
    talk_type   = models.ForeignKey(verbose_name=('カテゴリー'), to=TalkType, on_delete=models.PROTECT, null='True')
    user_id     = models.ForeignKey(verbose_name=('ユーザーID'), to=User, on_delete=models.PROTECT, null="True")
    # channels_id = models.ForeignKey(verbose_name=('チャンネルID'), null="True")

    def __str__(self):
        return self.talk

    class Meta:
        verbose_name_plural = "トーク"

class Alubum(models.Model):
    image       = models.ImageField(verbose_name=('画像'), upload_to='', null="True")
    talk_id     = models.ForeignKey(verbose_name=('トークID'), to=TalkModel, on_delete=models.PROTECT, null='False')

    _admin_list_display = ['image']

    # def __str__(self):
    #     return self.image
    
    class Meta:
        verbose_name_plural = "イメージ"

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LogInForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.contrib import messages
from tkinter import messagebox
# from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import SignUpForm#, LogInForm
from django.http import HttpResponseRedirect
from tkinter import messagebox

# Create your views here.
# @login_required
# def my_view(request):
class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

# class LogInView(generic.CreateView):
#     # form_class = LoginForm
#     template_name = "accounts/login.html"

def loginf(request):
    print('猫')
    if request.method == "POST":
        print('犬')
        new_username = request.POST['username']
        new_password = request.POST['password']
        user = authenticate(request, username=new_username, password=new_password)
        if user is not None:
            print('ニャン')
            login(request, user)
            return redirect('talk:list')
        else:
            print('わん')
            messages.error(request, 'ログインに失敗しました')
    return render(request,'accounts/login.html') 

# class LoginView(generic.CreateView):
#     def post(self, request, *arg, **kwargs):
#         form = LogInForm(data=request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             user = User.objects.get(username=username)
#             login(request, user)
#             return redirect('/')
#         return render(request, 'login.html', {'form': form,})

#     def get(self, request, *args, **kwargs):
#         form = LogInForm(request.POST)
#         return render(request, 'login.html', {'form': form,})

# account_login = LogInForm.as_view()

# class LoginView(generic.CreateView):
#     form_class = LogInForm
#     success_url = reverse_lazy('talk:list')
#     template_name = 'accounts/login.html'

talk/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.views.generic import ListView
# Create your views here.
class TalkViewBase(ListView):
    template_name = "talk/chatpage.html"
    model = models.TalkModel
    # queryset = models.TalkModel.objects.filter(some_column='')
    paginate_by = 20

    # def get_queryset(self):
    #     return models.TalkModel.objects.filter(publish=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["item"] = models.TalkModel.objects.order_by('-created')[:0]
        # context['talks'] = models.TalkModel.objects.created_at.order_by('-created')
        print(context)
        return context

templates/accounts/base.html
{% load static %}
{% load sass_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/base.css' %}">
    <link rel="stylesheet" href="{% sass_src 'assets/css/accounts.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'assets/css/chat.scss' %}">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <!-- <img src="{% static 'images/accounts.jpeg' %}" alt="画像" style="width: 100vw; height: 100vh; position: fixed;"> -->
      {% block content %}
      {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
  <div class="header">
    <h1>Log in</h1>
  </div>
  <div class="content">
    <form method="post">{% csrf_token %}
    <div class="form-position">
      <div class="nice-wrap">
        <input type="text" id="inputEmail" class="nice-textbox" name='username' placeholder="username" required autofocus>
        {{ form.username|add_class:'nice-textbox'|attr:'placeholder:お名前' }}
        {% if form.username.errors %}
          {{ form.username.errors }} 
        {% endif %}
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
    <div class="form-position">
      <div class="nice-wrap">
        <input type="password" id="inputPassword" class="nice-textbox" name='password' placeholder="Password" required>
        {{ form.password1|add_class:'nice-textbox'|attr:'placeholder:パスワード' }}
        {% if form.password1.errors %}
          {{ form.password1.errors }} 
        {% endif %}
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
    <div class="form-position">
      <div class="nice-wrap-submit">
        <button type="submit" class="btn btn-light" type="submit" name="education_form">ログイン</button>
        <label class="nice-label" for="Username"></label>
        {% if messages %}
        <ul class="messages" style="margin-top: 30px; color: red;">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        <div class="top-bar">
          <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-outline-dark">新規登録</button></a>
        </div>
      </div>
    </div>
  </form>
  </div>
</div>


<!-- <form class="form-signin" method="POST" action=''>{% csrf_token %}
  <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Please log in</h1> -->
  <!-- name で model と関連付けさせる -->
  <!-- <input type="text" id="inputEmail" class="form-control" name='username' placeholder="username" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label> -->
  <!-- name で model と関連付けさせる -->
  <!-- <input type="password" id="inputPassword" class="form-control" name='password' placeholder="Password" required>
  <div class="checkbox mb-3">
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">log in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
</form> -->
{{ form }}
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
  <div class="header">
    <h1>Sign up</h1>
  </div>
  <div class="content">
    <form method="post">{% csrf_token %}
    <div class="form-position">
      <div class="nice-wrap">
        {{ form.username|add_class:'nice-textbox'|attr:'placeholder:お名前' }}
        {% if form.username.errors %}
          {{ form.username.errors }} 
        {% endif %}
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
    <div class="form-position">
      <div class="nice-wrap">
        {{ form.email|add_class:'nice-textbox'|attr:'placeholder:email' }}
        {% if form.email.errors %}
          {{ form.email.errors }} 
        {% endif %}
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
    <div class="form-position">
      <div class="nice-wrap">
        {{ form.password1|add_class:'nice-textbox'|attr:'placeholder:パスワード' }}
        {% if form.password1.errors %}
          {{ form.password1.errors }} 
        {% endif %}
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
    <div class="form-position">
      <div class="nice-wrap">
        {{ form.password2|add_class:'nice-textbox'|attr:'placeholder:確認' }}
        {% if form.password2.errors %}
          {{ form.password2.errors }} 
        {% endif %}
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
    <div class="form-position">
      <div class="nice-wrap-submit">
        <button type="submit" class="btn btn-outline-dark" type="submit" name="education_form">登録</button>
        <label class="nice-label" for="Username"></label>
      </div>
    </div>
  </form>
  <div class="top-bar">
    <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-light" style="width: 120px; margin-left: 280px; margin-top: 5px;">ログイン</button></a>
  </div>
  </div>
</div>
  <!-- {{ form.first_name }}
<section class="common-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="submit">Sign up</button>
  </form>
</section>  -->
{% endblock %}

templates/talk/base.html
<!-- {% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="{% static 'assets/css/base.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="head">
      demo
    </div>
  </body>
  {% block title %}
    aaaaa
  {% endblock title %}
  {% block content %}

  {% endblock content %}
</html> -->

{% load static i18n %}
{% load i18n %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/flat-ui.min.css' %}" rel="stylesheet">
    <link href='netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet'/>
    <!-- css 変更中だが一度Html上にdjangoでの記述での確認のため -->
    <link rel="stylesheet" href="{% static 'assets/css/flat-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/footer.css' %}">  
    <link href='//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' />
    <!-- font -->
    <link href='//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>


<body>

<footer class="nb-footer">
  <div class="container">
    <div class="row">

      <div class="col-md-3 col-sm-6">
        <div class="footer-info-single">
          <h2 class="title">会社情報</h2>

          <ul class="follow-me">
            <li><a href="https://twitter.com"></a></li>
          </ul>
        </div>
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="footer-info-single">
          <h2 class="title">サービス</h2>
        </div>
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="footer-info-single">
          <h2 class="title">規約</h2>
          <ul class="list-unstyled">
                プライバシーポリシー</a></li>
        </div>
      </div>


    </div>
  </div>
  </div>
  </div>
  </div>
  </div>

  <section class="copyright">
    <div class="container">
      <div class="text-center">
        <p>©️ 2017 444 Inc. All Rights Reserved.</p>
      </div>
    </div>
  </div>
  </section>

</footer>


<!-- Bootstrap -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>
<!-- Bootstrap -->
</body>
</html>

templates/talk/chatpage.html
{% extends 'talk/base.html' %}
{% load static %}

{% block content %}
<!-- <div class="message-box">
  <div class="message-box_space"> -->
{% for item in object_list %}
  <div class="message-box">
    <div class="message-box_profile">
    </div>
    <div class="message-box_space">
      <div class="message-box_space_name">
        {{ item.user_id }}
        <div class="message-box_space_name_time">
          {{ item.created_at }}
        </div>
      </div>
      <div class="message-box_space_chatspase">
        {{ item.talk }}
        {{ item.talk_type }}
      </div>
    </div>
  </div>
{% endfor %}

<!-- {% for item in object_list %}
{{ item.talk }}
{{ item.created_at }}
{{ item.talk_type }}
{{ item.user_id }}
{% endfor %} -->

{% endblock content %}

templates/talk/talkbase.html
<!-- {% block title %}
aaaaa
{% endblock title %}
{% block content %}

{% endblock content %} -->

templates/user/base.html
{% load static %}
{% load sass_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/base.css' %}">
    <link rel="stylesheet" href="{% sass_src 'assets/css/base.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'assets/css/chat.scss' %}">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/user/create.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    <form method="POST" action="{% url 'create_account' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password1 }}
      {{ form.password1.errors }}
      <label>パスワード(確認)</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <button type = "submit">登録</button>
    </form>
  </body>
</html>

templates/user/index.html
{% extends 'user/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  {% if user.id  %}
    <p>ログインしました．</p>
    <p>こんにちは，{{ user.username }}さん</p>
    <a href="{% url 'logout' %}">ログアウトする</a>
    {% else %}
    <a href="{% url 'login' %}">ログイン</a>
    <a href="{% url 'create_account' %}">アカウント作成</a>
    {% endif %}
  <a href="{% url 'talk:list' %}"><input type="submit" value="ログイン" ></a>
</form>
{% endblock content %}

templates/user/login.html
{% extends 'user/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <a href="{% url 'talk:list' %}"><input type="submit" value="ログイン" ></a>
</form>
{% endblock content %}

templates/user/signup.html
{% block content %} 

<h2>ユーザー登録</h2>

<form method="post" action="{% url 'app:signup' %}">{% csrf_token %} 
    <label>ユーザー名</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認)</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <br>
    <input type="submit" value="登録する">
</form>

<p><a href="{% url 'app:login' %}">ログインはこちら</a></p> 

{% endblock %}